import Constanta from "./Constanta";
import Lambda from "./Lambda";

type PromiseType<Value> = Value extends Promise<infer Type> ? Type : Value;

type NAMESPACE = Record<string, Promise<Lambda | Constanta>>

type Map<Namespace extends NAMESPACE, Keys extends readonly (keyof _ArrayNamespace)[]> = Keys extends readonly [infer Key, ...infer Next]
  ? [PromiseType<Namespace[Key]>, ...Map<Next>]
  : []
;

type Load<Namespace extends NAMESPACE, Keys extends readonly keyof Namespace> = Promise<Map<Namespace, Keys>>

type NamespaceExec<Namespace extends NAMESPACE> = {
  <A extends keyof Namespace>(value: [A]): Promise<[PromiseType<Namespace[A]>]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
  >(value: readonly [A, B]): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
  >(
    value: readonly [A, B, C],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
  >(
    value: readonly [A, B, C, D],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
    E extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
    E extends keyof Namespace,
    F extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
    E extends keyof Namespace,
    F extends keyof Namespace,
    G extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>
  ]>;

  <
  A extends keyof Namespace,
  B extends keyof Namespace,
  C extends keyof Namespace,
  D extends keyof Namespace,
  E extends keyof Namespace,
  F extends keyof Namespace,
  G extends keyof Namespace,
  H extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>
  ]>;

  <
  A extends keyof Namespace,
  B extends keyof Namespace,
  C extends keyof Namespace,
  D extends keyof Namespace,
  E extends keyof Namespace,
  F extends keyof Namespace,
  G extends keyof Namespace,
  H extends keyof Namespace,
  I extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>
  ]>;

  <
  A extends keyof Namespace,
  B extends keyof Namespace,
  C extends keyof Namespace,
  D extends keyof Namespace,
  E extends keyof Namespace,
  F extends keyof Namespace,
  G extends keyof Namespace,
  H extends keyof Namespace,
  I extends keyof Namespace,
  J extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>
  ]>;

  <
  A extends keyof Namespace,
  B extends keyof Namespace,
  C extends keyof Namespace,
  D extends keyof Namespace,
  E extends keyof Namespace,
  F extends keyof Namespace,
  G extends keyof Namespace,
  H extends keyof Namespace,
  I extends keyof Namespace,
  J extends keyof Namespace,
  K extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>
  ]>;

  <
  A extends keyof Namespace,
  B extends keyof Namespace,
  C extends keyof Namespace,
  D extends keyof Namespace,
  E extends keyof Namespace,
  F extends keyof Namespace,
  G extends keyof Namespace,
  H extends keyof Namespace,
  I extends keyof Namespace,
  J extends keyof Namespace,
  K extends keyof Namespace,
  L extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>
  ]>;

  <
  A extends keyof Namespace,
  B extends keyof Namespace,
  C extends keyof Namespace,
  D extends keyof Namespace,
  E extends keyof Namespace,
  F extends keyof Namespace,
  G extends keyof Namespace,
  H extends keyof Namespace,
  I extends keyof Namespace,
  J extends keyof Namespace,
  K extends keyof Namespace,
  L extends keyof Namespace,
  M extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L, M],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>,
    PromiseType<Namespace[M]>
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
    E extends keyof Namespace,
    F extends keyof Namespace,
    G extends keyof Namespace,
    H extends keyof Namespace,
    I extends keyof Namespace,
    J extends keyof Namespace,
    K extends keyof Namespace,
    L extends keyof Namespace,
    M extends keyof Namespace,
    N extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L, M, N],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>,
    PromiseType<Namespace[M]>,
    PromiseType<Namespace[N]>
  ]>;

  <
  A extends keyof Namespace,
  B extends keyof Namespace,
  C extends keyof Namespace,
  D extends keyof Namespace,
  E extends keyof Namespace,
  F extends keyof Namespace,
  G extends keyof Namespace,
  H extends keyof Namespace,
  I extends keyof Namespace,
  J extends keyof Namespace,
  K extends keyof Namespace,
  L extends keyof Namespace,
  M extends keyof Namespace,
  N extends keyof Namespace,
  O extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>,
    PromiseType<Namespace[M]>,
    PromiseType<Namespace[N]>,
    PromiseType<Namespace[O]>
  ]>;

  <
  A extends keyof Namespace,
  B extends keyof Namespace,
  C extends keyof Namespace,
  D extends keyof Namespace,
  E extends keyof Namespace,
  F extends keyof Namespace,
  G extends keyof Namespace,
  H extends keyof Namespace,
  I extends keyof Namespace,
  J extends keyof Namespace,
  K extends keyof Namespace,
  L extends keyof Namespace,
  M extends keyof Namespace,
  N extends keyof Namespace,
  O extends keyof Namespace,
  P extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>,
    PromiseType<Namespace[M]>,
    PromiseType<Namespace[N]>,
    PromiseType<Namespace[O]>,
    PromiseType<Namespace[P]>,
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
    E extends keyof Namespace,
    F extends keyof Namespace,
    G extends keyof Namespace,
    H extends keyof Namespace,
    I extends keyof Namespace,
    J extends keyof Namespace,
    K extends keyof Namespace,
    L extends keyof Namespace,
    M extends keyof Namespace,
    N extends keyof Namespace,
    O extends keyof Namespace,
    P extends keyof Namespace,
    Q extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>,
    PromiseType<Namespace[M]>,
    PromiseType<Namespace[N]>,
    PromiseType<Namespace[O]>,
    PromiseType<Namespace[P]>,
    PromiseType<Namespace[Q]>,
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
    E extends keyof Namespace,
    F extends keyof Namespace,
    G extends keyof Namespace,
    H extends keyof Namespace,
    I extends keyof Namespace,
    J extends keyof Namespace,
    K extends keyof Namespace,
    L extends keyof Namespace,
    M extends keyof Namespace,
    N extends keyof Namespace,
    O extends keyof Namespace,
    P extends keyof Namespace,
    Q extends keyof Namespace,
    R extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>,
    PromiseType<Namespace[M]>,
    PromiseType<Namespace[N]>,
    PromiseType<Namespace[O]>,
    PromiseType<Namespace[P]>,
    PromiseType<Namespace[Q]>,
    PromiseType<Namespace[R]>
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
    E extends keyof Namespace,
    F extends keyof Namespace,
    G extends keyof Namespace,
    H extends keyof Namespace,
    I extends keyof Namespace,
    J extends keyof Namespace,
    K extends keyof Namespace,
    L extends keyof Namespace,
    M extends keyof Namespace,
    N extends keyof Namespace,
    O extends keyof Namespace,
    P extends keyof Namespace,
    Q extends keyof Namespace,
    R extends keyof Namespace,
    S extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>,
    PromiseType<Namespace[M]>,
    PromiseType<Namespace[N]>,
    PromiseType<Namespace[O]>,
    PromiseType<Namespace[P]>,
    PromiseType<Namespace[Q]>,
    PromiseType<Namespace[R]>,
    PromiseType<Namespace[S]>,
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
    E extends keyof Namespace,
    F extends keyof Namespace,
    G extends keyof Namespace,
    H extends keyof Namespace,
    I extends keyof Namespace,
    J extends keyof Namespace,
    K extends keyof Namespace,
    L extends keyof Namespace,
    M extends keyof Namespace,
    N extends keyof Namespace,
    O extends keyof Namespace,
    P extends keyof Namespace,
    Q extends keyof Namespace,
    R extends keyof Namespace,
    S extends keyof Namespace,
    T extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>,
    PromiseType<Namespace[M]>,
    PromiseType<Namespace[N]>,
    PromiseType<Namespace[O]>,
    PromiseType<Namespace[P]>,
    PromiseType<Namespace[Q]>,
    PromiseType<Namespace[R]>,
    PromiseType<Namespace[S]>,
    PromiseType<Namespace[T]>
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
    E extends keyof Namespace,
    F extends keyof Namespace,
    G extends keyof Namespace,
    H extends keyof Namespace,
    I extends keyof Namespace,
    J extends keyof Namespace,
    K extends keyof Namespace,
    L extends keyof Namespace,
    M extends keyof Namespace,
    N extends keyof Namespace,
    O extends keyof Namespace,
    P extends keyof Namespace,
    Q extends keyof Namespace,
    R extends keyof Namespace,
    S extends keyof Namespace,
    T extends keyof Namespace,
    U extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>,
    PromiseType<Namespace[M]>,
    PromiseType<Namespace[N]>,
    PromiseType<Namespace[O]>,
    PromiseType<Namespace[P]>,
    PromiseType<Namespace[Q]>,
    PromiseType<Namespace[R]>,
    PromiseType<Namespace[S]>,
    PromiseType<Namespace[T]>,
    PromiseType<Namespace[U]>
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
    E extends keyof Namespace,
    F extends keyof Namespace,
    G extends keyof Namespace,
    H extends keyof Namespace,
    I extends keyof Namespace,
    J extends keyof Namespace,
    K extends keyof Namespace,
    L extends keyof Namespace,
    M extends keyof Namespace,
    N extends keyof Namespace,
    O extends keyof Namespace,
    P extends keyof Namespace,
    Q extends keyof Namespace,
    R extends keyof Namespace,
    S extends keyof Namespace,
    T extends keyof Namespace,
    U extends keyof Namespace,
    V extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>,
    PromiseType<Namespace[M]>,
    PromiseType<Namespace[N]>,
    PromiseType<Namespace[O]>,
    PromiseType<Namespace[P]>,
    PromiseType<Namespace[Q]>,
    PromiseType<Namespace[R]>,
    PromiseType<Namespace[S]>,
    PromiseType<Namespace[T]>,
    PromiseType<Namespace[U]>,
    PromiseType<Namespace[V]>
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
    E extends keyof Namespace,
    F extends keyof Namespace,
    G extends keyof Namespace,
    H extends keyof Namespace,
    I extends keyof Namespace,
    J extends keyof Namespace,
    K extends keyof Namespace,
    L extends keyof Namespace,
    M extends keyof Namespace,
    N extends keyof Namespace,
    O extends keyof Namespace,
    P extends keyof Namespace,
    Q extends keyof Namespace,
    R extends keyof Namespace,
    S extends keyof Namespace,
    T extends keyof Namespace,
    U extends keyof Namespace,
    V extends keyof Namespace,
    W extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>,
    PromiseType<Namespace[M]>,
    PromiseType<Namespace[N]>,
    PromiseType<Namespace[O]>,
    PromiseType<Namespace[P]>,
    PromiseType<Namespace[Q]>,
    PromiseType<Namespace[R]>,
    PromiseType<Namespace[S]>,
    PromiseType<Namespace[T]>,
    PromiseType<Namespace[U]>,
    PromiseType<Namespace[V]>,
    PromiseType<Namespace[W]>,
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
    E extends keyof Namespace,
    F extends keyof Namespace,
    G extends keyof Namespace,
    H extends keyof Namespace,
    I extends keyof Namespace,
    J extends keyof Namespace,
    K extends keyof Namespace,
    L extends keyof Namespace,
    M extends keyof Namespace,
    N extends keyof Namespace,
    O extends keyof Namespace,
    P extends keyof Namespace,
    Q extends keyof Namespace,
    R extends keyof Namespace,
    S extends keyof Namespace,
    T extends keyof Namespace,
    U extends keyof Namespace,
    V extends keyof Namespace,
    W extends keyof Namespace,
    X extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>,
    PromiseType<Namespace[M]>,
    PromiseType<Namespace[N]>,
    PromiseType<Namespace[O]>,
    PromiseType<Namespace[P]>,
    PromiseType<Namespace[Q]>,
    PromiseType<Namespace[R]>,
    PromiseType<Namespace[S]>,
    PromiseType<Namespace[T]>,
    PromiseType<Namespace[U]>,
    PromiseType<Namespace[V]>,
    PromiseType<Namespace[W]>,
    PromiseType<Namespace[X]>
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
    E extends keyof Namespace,
    F extends keyof Namespace,
    G extends keyof Namespace,
    H extends keyof Namespace,
    I extends keyof Namespace,
    J extends keyof Namespace,
    K extends keyof Namespace,
    L extends keyof Namespace,
    M extends keyof Namespace,
    N extends keyof Namespace,
    O extends keyof Namespace,
    P extends keyof Namespace,
    Q extends keyof Namespace,
    R extends keyof Namespace,
    S extends keyof Namespace,
    T extends keyof Namespace,
    U extends keyof Namespace,
    V extends keyof Namespace,
    W extends keyof Namespace,
    X extends keyof Namespace,
    Y extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>,
    PromiseType<Namespace[M]>,
    PromiseType<Namespace[N]>,
    PromiseType<Namespace[O]>,
    PromiseType<Namespace[P]>,
    PromiseType<Namespace[Q]>,
    PromiseType<Namespace[R]>,
    PromiseType<Namespace[S]>,
    PromiseType<Namespace[T]>,
    PromiseType<Namespace[U]>,
    PromiseType<Namespace[V]>,
    PromiseType<Namespace[W]>,
    PromiseType<Namespace[X]>,
    PromiseType<Namespace[Y]>
  ]>;

  <
    A extends keyof Namespace,
    B extends keyof Namespace,
    C extends keyof Namespace,
    D extends keyof Namespace,
    E extends keyof Namespace,
    F extends keyof Namespace,
    G extends keyof Namespace,
    H extends keyof Namespace,
    I extends keyof Namespace,
    J extends keyof Namespace,
    K extends keyof Namespace,
    L extends keyof Namespace,
    M extends keyof Namespace,
    N extends keyof Namespace,
    O extends keyof Namespace,
    P extends keyof Namespace,
    Q extends keyof Namespace,
    R extends keyof Namespace,
    S extends keyof Namespace,
    T extends keyof Namespace,
    U extends keyof Namespace,
    V extends keyof Namespace,
    W extends keyof Namespace,
    X extends keyof Namespace,
    Y extends keyof Namespace,
    Z extends keyof Namespace,
  >(
    value: readonly [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z],
  ): Promise<[
    PromiseType<Namespace[A]>,
    PromiseType<Namespace[B]>,
    PromiseType<Namespace[C]>,
    PromiseType<Namespace[D]>,
    PromiseType<Namespace[E]>,
    PromiseType<Namespace[F]>,
    PromiseType<Namespace[G]>,
    PromiseType<Namespace[H]>,
    PromiseType<Namespace[I]>,
    PromiseType<Namespace[J]>,
    PromiseType<Namespace[K]>,
    PromiseType<Namespace[L]>,
    PromiseType<Namespace[M]>,
    PromiseType<Namespace[N]>,
    PromiseType<Namespace[O]>,
    PromiseType<Namespace[P]>,
    PromiseType<Namespace[Q]>,
    PromiseType<Namespace[R]>,
    PromiseType<Namespace[S]>,
    PromiseType<Namespace[T]>,
    PromiseType<Namespace[U]>,
    PromiseType<Namespace[V]>,
    PromiseType<Namespace[W]>,
    PromiseType<Namespace[X]>,
    PromiseType<Namespace[Y]>,
    PromiseType<Namespace[Z]>
  ]>;

} & Namespace;

export default NamespaceExec;
