export interface ObjectNamespace {
  public readonly align        : Promise<typeof import("./align").default>,
  public readonly eq           : Promise<typeof import("./eq").default>,
  public readonly each         : Promise<typeof import("./each").default>,
  public readonly isObject     : Promise<typeof import("./isObject").default>,
  public readonly isRecord     : Promise<typeof import("./isRecord").default>,
  public readonly has          : Promise<typeof import("./has").default>,
  public readonly exists       : Promise<typeof import("./exists").default>,
  public readonly prop         : Promise<typeof import("./prop").default>,
  public readonly propOr       : Promise<typeof import("./propOr").default>,
  public readonly path         : Promise<typeof import("./path").default>,
  public readonly props        : Promise<typeof import("./props").default>,
  public readonly omit         : Promise<typeof import("./omit").default>,
  public readonly pick         : Promise<typeof import("./pick").default>,
  public readonly pickOr       : Promise<typeof import("./pickOr").default>,
  public readonly where        : Promise<typeof import("./where").default>,
  public readonly whereEq      : Promise<typeof import("./whereEq").default>,
  public readonly whereIs      : Promise<typeof import("./whereIs").default>,
  public readonly whereNot     : Promise<typeof import("./whereNot").default>,
  public readonly whereNotEq   : Promise<typeof import("./whereNotEq").default>,
  public readonly whereNotIs   : Promise<typeof import("./whereNotIs").default>,
  public readonly map          : Promise<typeof import("./map").default>,
  public readonly mapEq        : Promise<typeof import("./mapEq").default>,
  public readonly mapIs        : Promise<typeof import("./mapIs").default>,

  public readonly onProp       : Promise<typeof import("./onProp").default>,
  public readonly onWhere      : Promise<typeof import("./onWhere").default>,
  public readonly onWhereEq    : Promise<typeof import("./onWhereEq").default>,
  public readonly onWhereIs    : Promise<typeof import("./onWhereIs").default>,
  public readonly onWhereNot   : Promise<typeof import("./onWhereNot").default>,
  public readonly onWhereNotEq : Promise<typeof import("./onWhereNotEq").default>,
  public readonly onWhereNotIs : Promise<typeof import("./onWhereNotIs").default>,
  public readonly onMap        : Promise<typeof import("./onMap").default>,
  public readonly onMapIs      : Promise<typeof import("./onMapIs").default>,
  public readonly onMapEq      : Promise<typeof import("./onMapEq").default>,
}

declare const ObjectNamespace: ObjectNamespace;
export default ObjectNamespace;
